name: smart_scan_amr
description: Digitizing handwritten prescriptions with integration into local antimicrobial inventory management and real-time national drug use surveillance.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image: ^4.5.4
  image_picker: ^1.1.2
  intl: ^0.19.0
  onnxruntime: ^1.4.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/models/decoder_int8.onnx
    - assets/models/encoder_int8.onnx
    - assets/models/tokenizer.json
    - assets/models/vocab.json
